[package]
name = "proven-queue-client"
version.workspace = true
edition.workspace = true

[dependencies]
proven-coordinator.workspace = true
proven-queue.workspace = true
proven-value.workspace = true
serde_json.workspace = true
thiserror.workspace = true
